In [1]:
import pandas as pd
data = pd.read_csv('insurance.csv')
data.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [2]:
data.shape

(1338, 7)

In [3]:
data.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [4]:
data[data.duplicated()]

age   sex    bmi  children smoker     region    charges
581   19  male  30.59         0     no  northwest  1639.5631

In [5]:
data.drop_duplicates()


age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [6]:
data = data.drop_duplicates().reset_index(drop=True)
data

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1332   50    male  30.970         3     no  northwest  10600.54830
1333   18  female  31.920         0     no  northeast   2205.98080
1334   18  female  36.850         0     no  southeast   1629.83350
1335   21  female  25.800         0     no  southwest   2007.94500
1336   61  female  29.070         0    yes  northwest  29141.36030

[1337 rows x 7 columns]

In [7]:
X = data.drop('charges',axis=1)

In [8]:
X


age     sex     bmi  children smoker     region
0      19  female  27.900         0    yes  southwest
1      18    male  33.770         1     no  southeast
2      28    male  33.000         3     no  southeast
3      33    male  22.705         0     no  northwest
4      32    male  28.880         0     no  northwest
...   ...     ...     ...       ...    ...        ...
1332   50    male  30.970         3     no  northwest
1333   18  female  31.920         0     no  northeast
1334   18  female  36.850         0     no  southeast
1335   21  female  25.800         0     no  southwest
1336   61  female  29.070         0    yes  northwest

[1337 rows x 6 columns]

In [9]:
y = data['charges']

In [10]:
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...     
1332    10600.54830
1333     2205.98080
1334     1629.83350
1335     2007.94500
1336    29141.36030
Name: charges, Length: 1337, dtype: float64

In [11]:
import numpy as np
X.sex = np.where(X.sex == 'female',0,1)

In [12]:
X.head()

age  sex     bmi  children smoker     region
0   19    0  27.900         0    yes  southwest
1   18    1  33.770         1     no  southeast
2   28    1  33.000         3     no  southeast
3   33    1  22.705         0     no  northwest
4   32    1  28.880         0     no  northwest

In [13]:
X.smoker = np.where(X.smoker == 'no',0,1)

In [43]:
X.head()

age  sex     bmi  children  smoker     region
0   19    0  27.900         0       1  southwest
1   18    1  33.770         1       0  southeast
2   28    1  33.000         3       0  southeast
3   33    1  22.705         0       0  northwest
4   32    1  28.880         0       0  northwest

In [44]:
X.region.unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [45]:
X = pd.get_dummies (X, columns= ['region'])

In [46]:
X.head()

age  sex     bmi  children  smoker  region_northeast  region_northwest  \
0   19    0  27.900         0       1                 0                 0   
1   18    1  33.770         1       0                 0                 0   
2   28    1  33.000         3       0                 0                 0   
3   33    1  22.705         0       0                 0                 1   
4   32    1  28.880         0       0                 0                 1   

   region_southeast  region_southwest  
0                 0                 1  
1                 1                 0  
2                 1                 0  
3                 0                 0  
4                 0                 0

In [51]:
from sklearn.model_selection import train_test_split

In [82]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=123)
X_train.shape

(935, 9)

In [72]:
#from sklearn.preprocessing import StandardScaler
#scaler = StandardScaler()
#scaler.fit_transform(X_train,y_train)
#scaler.transform(X_test,y_test)

In [73]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [74]:
ann = Sequential()

In [75]:
ann.add(Dense(units = 9,input_dim = X_train.shape[1],kernel_initializer = 'random_uniform',activation = 'relu'))

In [76]:
ann.add(Dense(units = 5,kernel_initializer = 'random_uniform',activation = 'relu'))

In [77]:
ann.add(Dense(units=1,kernel_initializer='random_uniform',activation = 'relu'))

In [78]:
ann.compile(loss = 'mean_squared_error',optimizer = 'adam')

In [79]:
ann.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 9)                 90        
                                                                 
 dense_4 (Dense)             (None, 5)                 50        
                                                                 
 dense_5 (Dense)             (None, 1)                 6         
                                                                 
Total params: 146
Trainable params: 146
Non-trainable params: 0
_________________________________________________________________


In [84]:
ann.fit(X_train,y_train,batch_size=15,epochs=500,validation_data=(X_test,y_test))

Epoch 1/500
63/63 [==============================] - 0s 2ms/step - loss: 38642188.0000 - val_loss: 34047212.0000
Epoch 2/500
63/63 [==============================] - 0s 2ms/step - loss: 38650256.0000 - val_loss: 34103572.0000
Epoch 3/500
63/63 [==============================] - 0s 2ms/step - loss: 38584596.0000 - val_loss: 34289676.0000
Epoch 4/500
63/63 [==============================] - 0s 2ms/step - loss: 38633012.0000 - val_loss: 34286904.0000
Epoch 5/500
63/63 [==============================] - 0s 2ms/step - loss: 38610480.0000 - val_loss: 34181220.0000
Epoch 6/500
63/63 [==============================] - 0s 2ms/step - loss: 38616280.0000 - val_loss: 34176632.0000
Epoch 7/500
63/63 [==============================] - 0s 2ms/step - loss: 38582556.0000 - val_loss: 34197240.0000
Epoch 8/500
63/63 [==============================] - 0s 2ms/step - loss: 38583492.0000 - val_loss: 34241944.0000
Epoch 9/500
63/63 [==============================] - 0s 2ms/step - loss: 38590444.0000 - val_los

Epoch 73/500
63/63 [==============================] - 0s 2ms/step - loss: 38529744.0000 - val_loss: 33922548.0000
Epoch 74/500
63/63 [==============================] - 0s 2ms/step - loss: 38502540.0000 - val_loss: 34139104.0000
Epoch 75/500
63/63 [==============================] - 0s 2ms/step - loss: 38493096.0000 - val_loss: 33906348.0000
Epoch 76/500
63/63 [==============================] - 0s 2ms/step - loss: 38521300.0000 - val_loss: 34026008.0000
Epoch 77/500
63/63 [==============================] - 0s 2ms/step - loss: 38495676.0000 - val_loss: 33927040.0000
Epoch 78/500
63/63 [==============================] - 0s 2ms/step - loss: 38500356.0000 - val_loss: 34032816.0000
Epoch 79/500
63/63 [==============================] - 0s 2ms/step - loss: 38472688.0000 - val_loss: 34054572.0000
Epoch 80/500
63/63 [==============================] - 0s 2ms/step - loss: 38505732.0000 - val_loss: 33961936.0000
Epoch 81/500
63/63 [==============================] - 0s 2ms/step - loss: 38501848.0000 

63/63 [==============================] - 0s 2ms/step - loss: 38349620.0000 - val_loss: 33815088.0000
Epoch 216/500
63/63 [==============================] - 0s 2ms/step - loss: 38367908.0000 - val_loss: 33828684.0000
Epoch 217/500
63/63 [==============================] - 0s 2ms/step - loss: 38408832.0000 - val_loss: 33727636.0000
Epoch 218/500
63/63 [==============================] - 0s 2ms/step - loss: 38342712.0000 - val_loss: 33715780.0000
Epoch 219/500
63/63 [==============================] - 0s 2ms/step - loss: 38346540.0000 - val_loss: 33801500.0000
Epoch 220/500
63/63 [==============================] - 0s 2ms/step - loss: 38389376.0000 - val_loss: 34091200.0000
Epoch 221/500
63/63 [==============================] - 0s 2ms/step - loss: 38343888.0000 - val_loss: 33934764.0000
Epoch 222/500
63/63 [==============================] - 0s 2ms/step - loss: 38314224.0000 - val_loss: 33817276.0000
Epoch 223/500
63/63 [==============================] - 0s 2ms/step - loss: 38329644.0000 - val

63/63 [==============================] - 0s 2ms/step - loss: 38043968.0000 - val_loss: 33429660.0000
Epoch 358/500
63/63 [==============================] - 0s 2ms/step - loss: 37988372.0000 - val_loss: 33586872.0000
Epoch 359/500
63/63 [==============================] - 0s 2ms/step - loss: 38002996.0000 - val_loss: 33640444.0000
Epoch 360/500
63/63 [==============================] - 0s 2ms/step - loss: 37976488.0000 - val_loss: 33485732.0000
Epoch 361/500
63/63 [==============================] - 0s 2ms/step - loss: 37981260.0000 - val_loss: 33460176.0000
Epoch 362/500
63/63 [==============================] - 0s 2ms/step - loss: 38027112.0000 - val_loss: 33508774.0000
Epoch 363/500
63/63 [==============================] - 0s 2ms/step - loss: 38001352.0000 - val_loss: 33327580.0000
Epoch 364/500
63/63 [==============================] - 0s 2ms/step - loss: 38074472.0000 - val_loss: 33371740.0000
Epoch 365/500
63/63 [==============================] - 0s 2ms/step - loss: 38038452.0000 - val

63/63 [==============================] - 0s 2ms/step - loss: 36757580.0000 - val_loss: 32150726.0000
Epoch 500/500
63/63 [==============================] - 0s 2ms/step - loss: 36743648.0000 - val_loss: 32177140.0000


In [86]:
y_pred = ann.predict(X_test)

13/13 [==============================] - 0s 852us/step


In [88]:
y_pred

array([[ 1334.9009 ],
       [16091.819  ],
       [26258.354  ],
       [ 2100.0898 ],
       [13102.072  ],
       [ 8341.988  ],
       [10251.622  ],
       [ 9323.729  ],
       [ 5707.2354 ],
       [33533.99   ],
       [ 6135.6807 ],
       [12848.307  ],
       [ 5138.9995 ],
       [13814.906  ],
       [11026.478  ],
       [29407.887  ],
       [12791.718  ],
       [29938.55   ],
       [36220.938  ],
       [ 6233.1416 ],
       [37789.418  ],
       [13368.878  ],
       [  757.86993],
       [ 6607.8306 ],
       [27356.613  ],
       [11917.138  ],
       [14826.907  ],
       [13820.458  ],
       [ 2502.0889 ],
       [38115.63   ],
       [ 2704.1362 ],
       [11868.718  ],
       [14587.497  ],
       [ 3857.915  ],
       [ 9313.315  ],
       [10919.097  ],
       [37284.02   ],
       [ 4091.651  ],
       [37319.918  ],
       [29311.195  ],
       [ 6646.687  ],
       [ 6529.229  ],
       [28628.982  ],
       [13652.518  ],
       [ 2406.5647 ],
       [35

In [89]:
y_train

616     23306.54700
373     36085.21900
299      9249.49520
376     21659.93010
384      8302.53565
           ...     
1238     3238.43570
1147    10791.96000
106      2331.51900
1041    33475.81715
1122    18903.49141
Name: charges, Length: 935, dtype: float64

In [90]:
y_train[0]-y_pred[0]

array([15550.023], dtype=float32)

###REAL TIME PREDICTIONS

In [93]:
ann.predict([[30,0,18.5,3,0,0,1,0,0]])

1/1 [==============================] - 0s 61ms/step


array([[4440.0195]], dtype=float32)